server:
  port: 4002
  url: http://k8s-default-backuser-6b57e68a13-2063567931.ap-northeast-2.elb.amazonaws.com/

spring:
  application:
    name: capstone
  redis:
    port: 6379
    host: http://my-redis.redis-ns.svc.cluster.local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://exqress-db.ctxktr2nwban.ap-northeast-2.rds.amazonaws.com:3306/delivery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: qwer1234
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

greeting:
  message: Welcome to the exqress-user-service!

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  access_expiration_time: 86400
  refresh_expiration_time: 8640000
  secret: exqress-token

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**