server:
  port: 4002

spring:
  application:
    name: capstone
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
    # url: jdbc:mysql://exqress-rds.ctxktr2nwban.ap-northeast-2.rds.amazonaws.com:3306/exqressdb/useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

greeting:
  message: Welcome to the exqress-user-service!

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  access_expiration_time: 86400
  refresh_expiration_time: 8640000
  secret: exqress-token